# Generated by Django 5.2.4 on 2025-07-28 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryImage', models.ImageField(upload_to='categories/')),
                ('categoryName', models.CharField(max_length=100)),
                ('categoryDescription', models.TextField()),
                ('categoryStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(upload_to='products/')),
                ('productName', models.CharField(max_length=100)),
                ('ProductSku', models.CharField(max_length=50, unique=True)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productStatus', models.BooleanField(default=True)),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodai_app.category')),
            ],
        ),
    ]
