# Generated by Django 5.2.4 on 2025-08-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodai_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
