# Generated by Django 5.2.4 on 2025-07-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodai_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryStatus',
            field=models.TextField(max_length=10),
        ),
    ]
