# Generated by Django 5.2.4 on 2025-07-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodai_app', '0002_alter_category_categorystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductNumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
