# Generated by Django 5.2.4 on 2025-08-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodai_app', '0002_alter_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
