# Generated by Django 5.2.4 on 2025-08-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodai_app', '0003_product_productnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productStatus',
            field=models.TextField(max_length=10),
        ),
    ]
