# Generated by Django 5.2.4 on 2025-08-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodai_app', '0003_alter_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryImage',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
