# Generated by Django 5.2.4 on 2025-08-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodai_app', '0004_alter_category_categoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryImage',
            field=models.URLField(blank=True, max_length=100000, null=True),
        ),
    ]
