# Generated by Django 5.2.4 on 2025-08-04 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodai_app', '0004_alter_product_productstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerEmail', models.CharField(max_length=50, unique=True)),
                ('customerLocation', models.CharField(max_length=50)),
                ('customerOrders', models.IntegerField(blank=True, default=0, null=True)),
                ('cashSpent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.CharField(max_length=50)),
                ('OrderNumber', models.IntegerField(blank=True, default=0, null=True)),
                ('datePurchased', models.DateTimeField()),
                ('paymentMethod', models.CharField(max_length=50)),
                ('amountPaid', models.FloatField(blank=True, default=0, null=True)),
                ('CustomerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodai_app.customers')),
            ],
        ),
    ]
