# Generated by Django 5.2.4 on 2025-08-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodai_app', '0005_customers_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderStatus',
            field=models.CharField(default='draft', max_length=100),
            preserve_default=False,
        ),
    ]
